version: '3.3'

services:
  api:
    container_name: discord-api
    image: discord-api-image
    build:
      dockerfile: ./docker/Dockerfile.backend.dev
      context: .
    volumes:
      - ./apps/fastify-api:/app/apps/fastify-api
      - ./types:/app/types
      - ./configs:/app/configs
    ports:
      - ${BE_PORT}:${BE_PORT}
    env_file:
      - .env

  frontend:
    container_name: discord-frontend
    image: discord-frontend-image
    build:
      dockerfile: ./docker/Dockerfile.frontend.dev
      context: .
    ports:
      - 4200:4200
    volumes:
      - ./apps/discord-clone-v2:/app/apps/discord-clone-v2
      - ./types:/app/types
      - ./configs:/app/configs
    env_file:
      - .env


