version: '3.3'

services:
  api:
    container_name: discord-api
    image: discord-api-image
    build:
      dockerfile: ./docker/Dockerfile.backend.dev
      context: .
    volumes:
      - ./apps/fastify-api:/app/apps/fastify-api
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.base.json:/app/tsconfig.base.json
      - ./shared:/app/shared
    ports:
      - ${BE_PORT}:${BE_PORT}
    env_file:
      - .env

  frontend:
    container_name: discord-frontend
    image: discord-frontend-image
    build:
      dockerfile: ./docker/Dockerfile.frontend.dev
      context: .
    ports:
      - 4200:4200
    volumes:
      - ./apps/discord-clone-v2:/app/apps/discord-clone-v2
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.base.json:/app/tsconfig.base.json
      - ./shared:/app/shared
    env_file:
      - .env

  studio:
    container_name: discord-studio
    image: discord-studio-image
    build:
      dockerfile: ./docker/Dockerfile.studio.dev
      context: .
    ports:
      - 5555:5555
    volumes:
      - ./apps/fastify-api:/app/apps/fastify-api
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.base.json:/app/tsconfig.base.json
      - ./shared:/app/shared
    env_file:
      - .env


