global:
  checkNewVersion: true
  sendAnonymousUsage: true

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
    http:
      tls:
        certResolver: default

certificatesResolvers:
  default:
    acme:
      email: kacper.hemperek@o2.pl
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
      caserver: https://acme-v02.api.letsencrypt.org/directory

providers:
  docker:
    exposedByDefault: false
