version: '3.3'

services:
  frontend:
    image: frontend
    build:
      context: ./docker
      dockerfile: Dockerfile.frontend
    ports:
      - 80:80
      - 433:433

  backend:
    image: backend
    build:
      context: ./docker
      dockerfile: Dockerfile.backend
    ports:
      - 4444:4444
    environment:
      - PORT=4444
      - HOST=0.0.0.0

